spring.application.name=flower-billing-system
spring.datasource.url=jdbc:h2:file:./db/flowershop;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security properties
app.jwt.secret=9a674738-d6a1-4f18-ad4e-4b680786cf8c9a674738d6a14f18ad4e4b680786cf8c
app.jwt.expiration-ms=3600000
